#pragma once
#ifndef MACRO_HEADER
#define MACRO_HEADER

#define MASTER 0

#define START_TAG 0
#define FINISH_PROCESS_TAG 1
#define FINISH_TASK_TAG 2
#define ALPHA_NOT_FOUND 0
#define ALPHA_FOUND 1
#define ALPHA_POTENTIALLY_FOUND 2


#define BUFFER_SIZE 1000
#endif // !MACRO_HEADER